version: '2'

services:
  project-rally-point-database:
    container_name: project-rally-point-database
    image: postgres:10.1
    ports:
      - 8081:5432
    environment:
      POSTGRES_USER: project_rally_point
      POSTGRES_PASSWORD: password
